# Generated by Django 5.2.8 on 2025-11-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=64)),
                ('species', models.CharField(max_length=64)),
                ('binomial', models.CharField(max_length=140, unique=True)),
                ('english_cname', models.CharField(blank=True, default='', max_length=140)),
                ('habitat', models.TextField(blank=True, default='')),
                ('diet', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('image_url_1', models.URLField(blank=True, default='')),
                ('image_url_2', models.URLField(blank=True, default='')),
                ('image_url_3', models.URLField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['genus', 'species'], name='birds_bird_genus_e74404_idx'), models.Index(fields=['binomial'], name='birds_bird_binomia_6b1b97_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('predicted_label', models.CharField(max_length=140)),
                ('confidence', models.FloatField()),
                ('top_votes_json', models.JSONField(default=dict)),
                ('matched_bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birds.bird')),
            ],
        ),
    ]
